services:
  - type: web
    name: new-eridian-seed-api
    runtime: docker
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_KEY
        generateValue: true
      - key: MOD_KEY
        generateValue: true
      - key: TWITCH_API_KEY
        generateValue: true
      - key: GAME_NAME
        value: New Eridian
