"""Workstation tiers shared by the catalog graph and workshop access rules.

Kept in a leaf module so the SEED catalog can rank recipes by the progression a
player actually needs (station tier and skill) without importing the workshop.
"""

SURVIVAL='TAG_MACHINE_SURVIVAL_WORKBENCH'
TAG_TIERS={
 SURVIVAL:1,'TAG_MACHINE_CRAFTING_TABLE_V1':1,'TAG_MACHINE_CRAFTING_TABLE_V2':2,'TAG_MACHINE_CRAFTING_TABLE_V3':3,
 'TAG_MACH_SIMPLE_CARPENTRY_STATION':1,'TAG_MACHINE_ADVANCED_CARPENTRY_STATION':2,
 'TAG_MACHINE_BASIC_FURNACE':1,'TAG_MACHINE_BASIC_ANVIL':1,'TAG_MACHINE_METALWORKING_BENCH':1,
 'TAG_MACHINE_MASONRY':1,'TAG_MACHINE_KILN':1,'TAG_MACHINE_POTTERY_STATION':1,
 'TAG_MACHINE_FOOD_PROCESSOR':1,'TAG_MACHINE_CAMPFIRE':1,'TAG_MACHINE_STOVE':2,'TAG_MACHINE_OVEN':2,
 'TAG_MACHINE_SEED_SEPARATOR':1,'TAG_MACH_PROD_WATER_FILTRATION_SMALL':1,'TAG_MACH_EXT_WATER':1,
 'TAG_MACHINE_MEDICAL_FABRICATOR':1,'TAG_MACHINE_TAILORING_BENCH':2,'TAG_MACHINE_WEAVING_LOOM':1,
 'TAG_MACHINE_CHEMISTRY_STATION':2,'TAG_MACHINE_MILLING_MACHINE':2,'TAG_MACHINE_MINERAL_SEPARATOR':2,
 'TAG_MACHINE_METAL_LATHE':3,'TAG_MACHINE_ROLLING_MILL':3,'TAG_MACHINE_WIRE_DRAWER':2,
 'TAG_MACHINE_TABLE_SAW':3,'TAG_MACHINE_ELECTRONICS_TABLE':3,'TAG_MACHINE_FURNACE':3,
 'TAG_MACHINE_STONE_GRINDER':3,'TAG_MACH_PROD_WATER_FILTRATION':2,'TAG_MACHINE_EXTRACTOR':3,
 'TAG_MACHINE_GROWBOX':4,'TAG_MACHINE_3D_PRINTER':4,'TAG_MACHINE_PLAXIN_SYNTHESIZER':4,
}
# Catalog entries without machine tags get explicit appropriate workstations.
OVERRIDES={'sr_1501328773':['TAG_MACHINE_STOVE'],'sr_1187763008':['TAG_MACHINE_CRAFTING_TABLE_V3'],
           'sr_26415128':['TAG_MACHINE_GROWBOX']}


def recipe_tags(recipes, recipe):
    return OVERRIDES.get(recipe, recipes[recipe]['machines'])


def station_tier(recipes, recipe):
    return min(TAG_TIERS[tag] for tag in recipe_tags(recipes, recipe))
