"""Twitch-specific handbook; syntax matches the bundled StreamElements templates."""
TOPICS = {
    "start": "New Eridian v2: !start, !job farmer, then !guide. Work, !eat, !make and !gather have a 5-second cooldown; !sleep fully restores Energy and Comfort once every 30 minutes. Social/recovery timers vary; !cooldowns shows yours. Link accounts with !link, then enter that code using /link in Discord.",
    "character": "!status: needs, queue, cooldowns and what is ready, in one line. !me: citizen. !skills: twelve skills. !life: needs. !bonuses: active boosts. !cooldowns: timers. !contracts: daily task. !achievements and !collection: progress. !job farmer, miner, technician, researcher, courier, explorer, merchant, harvester, processor, engineer, artisan, cook, medic, pharmacist, firefighter, safety_officer. !specialize <path>: permanent Lv.10 path. !titles <title>: equip unlocked title.",
    "property": "!make: the Workbench (categories with ready counts). !make <category> [page]: recipes easiest first, e.g. !make parts 2 or !make food. !make <recipe name or id>: craft one batch, e.g. !make Iron Plate (close spellings work). !make ready: everything craftable now. !fav <recipe>: star a recipe; !make favs lists them. !fetch <recipe> [batches]: plan its missing ingredients; !fetchgo starts gathering, then crafts. Categories: materials, parts, food, medicine, seeds, equipment, machines, building, beds, seating, bathroom, clothing, storage, tables, decor. !workshop: station access and tiers (0/25/100/250 batches). !workshopunlock <station id>: one-time fee. !seedpage 1 and !seedbuy <item> <qty>: supplies. !home and !homeup: Habitat (SC + Iron Nails). !business commands: company.",
    "life": "Passive recovery: +1 to all needs every 15 minutes, capped at 60. !life: Energy, Nutrition, Social, Comfort, Morale. Every task costs as much Comfort as Energy (standard: 2 Energy, 1 Nutrition, 2 Comfort); !relax gives +20 Comfort. Comfort below 20 slows work; below 10 blocks it. !sleep restores Energy and Comfort to 100 once every 30 minutes; between sleeps use !relax or !use a bed, seat, bath or clothing item. !eat: raw food +10 Nutrition, prepared food +15 to +50 and Rocky's Favor. !games restores Social. Work needs Energy/Nutrition/Social 20+ and Comfort 10+. !recover uses every recovery that is ready. !settings autorecover on lets paused queues recover themselves; !settings alerts quiet|off|mention sets queue alerts.",
    "production": "!gather: natural materials; !gatherpage 2: more. !gather <name/id>: collect. !catalog <name/id>: exact ingredient source. Old material names share stock with catalog items (Crops = Pumpkin, Components = Iron Nails). Rare ores: Harvesting Lv3, three successful prospecting actions per ore, 20s cooldown. !farm and !harvest: Farming (Pumpkins). !water and !scan: Processing. !mine <ore ID> <1–10>: queue mining. !queue, !queuecancel, !queuetasks <search>, !queueadd <task ID> <1–10>: queues. !queuenext <task ID> <1–10>: run after the current queue. !queuerepeat: run the last queue again. !make <recipe>: Crafting. !repair: Engineering. !research: Research.",
    "operations": "!cargo prepares Cargo; !delivery consumes it on success. !spaceport: Logistics. !explore: Frontier; !survey requires a Resource Scanner. !market: Commerce work. !marketboard: prices. !sell ore: sell a resource. !sellall <item>: sell all of one item to Seed Industries. !clearout: preview selling surplus materials (keeps 20 of each and anything your favourites or queues use); !clearout confirm sells. !inv <search|value|ready> [page]: search and sort your inventory. !seedindustries buy <item>: buy supplies; !seedindustries orders: production orders. !ducks Asimov: choose a delivery partner.",
    "society": "!society: society. !progress: next society tier. !leaderboard: contributions. !world, !conditions, !bulletin, !story, !projectstatus: world details. !event and !eventhistory: events. !guide event: help. Primary success adds 1; two support successes add 1. Expiry below 75%: full penalty; 75–99%: half; completed: rewards.",
    "other": "!district <district> and !shift <role>: location/work role. !meal: contribute a Pumpkin. !use <item>: use an owned item (beds, seats, baths and clothing restore Comfort and are kept). !gearrepair <item>: repair owned gear with Iron Nails. !traits, !relationships, !journal, !tutorial: personal details. !mentor <name>: help a citizen. !display compact or detailed: result detail. Shortcuts: !again repeats your last action. !craftmax <recipe or resource> queues as many as you can. !target <recipe> pins a goal (!target shows the next step). !routines and !routine <n>: saved queue plans. !uses <item>: recipes that use it. !autosell <item>: sell it when queues finish. !undo: take back a sale within 60s. !eatfull: eat to 80 Nutrition. !find <word>: search everything.",
    "moderator": "Moderator templates: !sirostart/!siroend, !foodstart/!foodend, !miningstart/!miningend, !deliverystart/!deliveryend, !marketstart/!marketend. Start begins an event; end cancels it without a failure penalty. !nextday advances the day. Moderator commands require the configured admin key; never paste the key in public chat.",
    "terms": "SC means Seed Coin: personal currency. Contribution tracks society service. Aptitudes are twelve skill families; fractional practice carries into whole XP. Commerce is an aptitude, not a crafting category. Workbench categories list recipes easiest first by tier, skill level and crafting steps. Every item is a SEED catalog item; old names still work. Personal inventory and shared settlement stocks are separate.",
}
