
"""Twitch-specific handbook; syntax matches the bundled StreamElements templates."""
TOPICS = {
    "start": "New Eridian v2: !start, !job farmer, then !guide. Work, !eat and !sleep have a shared 5-second cooldown. Social/recovery timers vary; !cooldowns shows yours. !make has no cooldown. Link accounts with !link, then enter that code using /link in Discord.",
    "character": "!me: citizen. !skills: twelve skills. !life: needs. !bonuses: active boosts. !cooldowns: timers. !contracts: daily task. !achievements and !collection: progress. !job farmer, miner, technician, researcher, courier, explorer, merchant, harvester, processor, engineer, artisan, cook, medic, pharmacist, firefighter, safety_officer. !specialize <path>: permanent Lv.10 path. !titles <title>: equip unlocked title.",
    "property": "!home and !homeup: inspect/upgrade Habitat. !business, !businessstart <name>, !businesswork, !businesscontract, !businessinvest: company. !make: browse. !make basic_components or advanced_components or final_products: category. !make component: craft. !recipes tree: dependencies. !inventory and !gear: supplies/equipment. !seedindustries buy ore: trade parts.",
    "life": "!life: Energy, Nutrition, Social, Comfort, Morale. !eat uses Ration (+70 Nutrition) or Crop (+35); starving without food gets emergency recovery to 40. !sleep restores Energy/Comfort to 100. !games restores Social without a partner. !relax, !walk, !hobby games: recovery. !hi <name>, !hangout <name>, !duo <name> walk: social. Work needs Energy/Nutrition/Social at least 20.",
    "production": "!farm and !harvest: Farming. !water and !scan: Processing. !mine and !rare: Harvesting. !make <recipe>: Crafting. !repair: Engineering. !research: Research. Success gives the listed rewards and condition-dependent aptitude practice; failures give no success rewards. Determination improves the next attempt in that aptitude. !guide aptitude suggests training.",
    "operations": "!cargo prepares Cargo; !delivery consumes it on success. !spaceport: Logistics. !explore: Frontier; !survey requires a Sensor. !market: Commerce work. !marketboard: prices. !sell ore: sell a resource. !seedindustries buy ore: buy parts; !seedindustries orders: production orders. !ducks Asimov: choose a delivery partner.",
    "society": "!status: society. !progress: next society tier. !leaderboard: contributions. !world, !conditions, !bulletin, !story, !projectstatus: world details. !event and !eventhistory: events. !guide event: help. Primary success adds 1; two support successes add 1. Expiry below 75%: full penalty; 75–99%: half; completed: rewards.",
    "other": "!district <district> and !shift <role>: location/work role. !meal: contribute a Crop. !use <item>: consume crafted life item. !gearrepair <item>: repair owned gear. !traits, !relationships, !journal, !tutorial: personal details. !mentor <name>: help a citizen. !display compact or detailed: result detail.",
    "moderator": "Moderator templates: !sirostart/!siroend, !foodstart/!foodend, !miningstart/!miningend, !deliverystart/!deliveryend, !marketstart/!marketend. Start begins an event; end cancels it without a failure penalty. !nextday advances the day. Moderator commands require the configured admin key; never paste the key in public chat.",
    "terms": "SC means Seed Coin: personal currency. Contribution tracks society service. Aptitudes are twelve skill families; fractional practice carries into whole XP. Farming uses the saved cultivation key. Commerce is an aptitude, not a crafting category. Craft categories: Raw Materials, Basic Components, Advanced Components, Final Products, Production Tree. Personal inventory and shared settlement stocks are separate.",
}
